### ISSUE TITLE
AnsibleRunnerV2 broken on upstream changes to PlaybookCLI in devel

### ISSUE THREAD

**Issue by jctanner** [philpep/testinfra#401]
```
(venv) [jtanner@jtw530 role.1]$ python -c 'from testinfra.utils.ansible_runner import AnsibleRunnerV2; runner = AnsibleRunnerV2()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/workspace.issues/AP-MOLECULE_COLLECTION_INIT/venv/lib/python3.7/site-packages/testinfra-1.16.0-py3.7.egg/testinfra/utils/ansible_runner.py", line 153, in __init__
    self.cli.options = self.cli.base_parser(
AttributeError: 'PlaybookCLI' object has no attribute 'base_parser'
(venv) [jtanner@jtw530 role.1]$
```

Caused by https://github.com/ansible/ansible/commit/7e92ff823e2bf97ee33c1b7ff87bb8acecb5ae77#diff-b54c875fc6bfd4d98dcc488f06a07bea

**Comment by singuliere** [comment]
The commit introducing the change, from the PR and before the squash post merge: https://github.com/ansible/ansible/pull/50069/commits/39e4421af26584863eb69d8ac01d44c66676c290

**Comment by cboylan** [comment]
Using https://github.com/ansible/ansible-runner may be more reliable long term method of running ansible from testinfra. I don't have enough knowledge around testinfra or ansible-runner to know for sure, but wanted to make sure this alternative was called out since ansible-runner seems built for this exact use case.

**Comment by jctanner** [comment]
I've already started a port to runner and it's only held up right now by an obscure bug: https://github.com/ansible/ansible-runner/issues/200

**Comment by ianw** [comment]
@jctanner thanks for that; I took that gist and got it working for at least a loopback situation and will test more.  I missing what was happening with the event capture, ascii codes and molecule, but I hope that with you as the author it can be fixed.  OpenStack should be able to test that pull request as it progresses in our CI too, as an extra level of testing over travis

**Comment by philpep** [comment]
Great ! +1 for using ansible-runner

**Comment by decentral1se** [comment]
:rocket: :rocket: :rocket: 

`ansible-runner` integration would indeed be fantastic.

**Comment by philpep** [comment]
Hi, I just released 3.0.0 with the new ansible runner which should be compatible with ansible 2.8 please sse the changelog here: https://testinfra.readthedocs.io/en/latest/changelog.html
